In [1]:
import numpy as np

In [8]:
random_arr=np.random.random((2,2))
random_arr

array([[0.77673672, 0.4456062 ],
       [0.44728735, 0.25061302]])

In [9]:
identity=np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:", arr.shape)
print("Size:",arr.size)
print("Data type:", arr.dtype)
arr.ndim

Shape: (2, 3)
Size: 6
Data type: int64


2

In [14]:
a1=np.array([1,2,3,4])
a2=np.array([3,4,5,6])
a1+a2

array([ 4,  6,  8, 10])

In [19]:
a1=np.array([[1,2,3],[7,8,9],[4,5,6]])
a2=np.array([[4,5,6],[9,8,7],[1,2,3]])
a2*a1


array([[ 4, 10, 18],
       [63, 64, 63],
       [ 4, 10, 18]])

In [21]:
np.dot(a1,a2)

array([[ 25,  27,  29],
       [109, 117, 125],
       [ 67,  72,  77]])

In [22]:
# sum mean std max min
np.std(a1)

np.float64(2.581988897471611)

In [35]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
arr.reshape(2,5)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [37]:
np.vstack(arr)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [38]:
np.hstack(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr=np.array([1,2,3])
view= arr.view()
view[0]=10
print(arr)
copy=arr.copy()
copy[0]=100
print(arr)

[10  2  3]
[10  2  3]
